name: Run Tests in my project every push on GitHub

on: [push]

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout latest code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 20.x
    - name: Run npm install
      run: npm install
    - name: Run tests
      uses: tangro/actions-test@v1.1.28
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_CONTEXT: ${{ toJson(github) }}